development:
  adapter: postgresql
  host: 127.0.0.1
  username: postgres
  password: mypass
  pool: 5

test:
  adapter: postgresql
  host: 127.0.0.1
  username: postgres
  password: mypass
  pool: 5

production:
  adapter: postgresql
  host: 127.0.0.1
  username: postgres
  password: mypass
  pool: 5
